// ignore_for_file: public_member_api_docs,constant_identifier_names,type=lint,unused_element,unused_field
import 'package:flutter/foundation.dart';

//
// GENERATED CODE - DO NOT MODIFY BY HAND
// **************************************************************************
// Generated by flutter-assets-generator extension for VS Code
// @mrasityilmaz
// **************************************************************************

@immutable
final class Assets {
  Assets._();
  static final _Fonts fonts = _Fonts._();
  static final _Images images = _Images._();
}

@immutable
final class _Fonts {
  _Fonts._();

  final String inter_18pt_bold_ttf = 'assets/fonts/Inter_18pt-Bold.ttf';
  final String inter_18pt_extrabold_ttf =
      'assets/fonts/Inter_18pt-ExtraBold.ttf';
  final String inter_18pt_light_ttf = 'assets/fonts/Inter_18pt-Light.ttf';
  final String inter_18pt_medium_ttf = 'assets/fonts/Inter_18pt-Medium.ttf';
  final String inter_18pt_regular_ttf = 'assets/fonts/Inter_18pt-Regular.ttf';
  final String inter_18pt_semibold_ttf = 'assets/fonts/Inter_18pt-SemiBold.ttf';
}

@immutable
final class _Images {
  _Images._();

  final String app_icon_png = 'assets/images/app_icon.png';
  final String app_splash_png = 'assets/images/app_splash.png';
  final String email_svg = 'assets/images/email.svg';
  final String loading_svg = 'assets/images/Loading.svg';
  final String lock_svg = 'assets/images/lock.svg';
  final String logo_svg = 'assets/images/logo.svg';
  final String onboarding_1_svg = 'assets/images/onboarding_1.png';
  final String onboarding_2_svg = 'assets/images/onboarding_2.png';
  final String onboarding_3_svg = 'assets/images/onboarding_3.png';
  final String splash_svg = 'assets/images/Splash.svg';
  final String success_svg = 'assets/images/success.svg';
  final String user_svg = 'assets/images/user.svg';
}
